server:
  port: 8082

#jdbc
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wintermall
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: lyj
    password: lyj
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis
    max-wait: -1
    max-idle: 8
    min-idle: 0
    max-active: 10
    timeout: 30000

#mybatis
mybatis:
  type-aliases-package: com.bdqn.order.pojo
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

socket:
  port: 18089

